version: 2
jobs:
  checkout_and_install:
    docker:
      - image: dydxprotocol/node:12.18.3-alpine
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Environment.DEP_CACHE_VERSION }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Environment.DEP_CACHE_VERSION }}-{{ .Branch }}-
            - dependency-cache-{{ .Environment.DEP_CACHE_VERSION }}-
      - run:
          name: Install Dependencies
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc && npm ci
      - save_cache:
          key: dependency-cache-{{ .Environment.DEP_CACHE_VERSION }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "$HOME/.npm"
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build
  lint:
    docker:
      - image: dydxprotocol/node:12.18.3-alpine
    working_directory: ~/build
    steps:
      - restore_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: npm run lint
  build:
    docker:
      - image: dydxprotocol/node:12.18.3-alpine
    working_directory: ~/build
    steps:
      - restore_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: cache-completed-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build
  test:
    docker:
      - image: dydxprotocol/node:12.18.3-alpine
      - image: trufflesuite/ganache-cli:v6.8.2
        command: -d -k=istanbul -i 1001
    working_directory: ~/build
    steps:
      - restore_cache:
          key: cache-completed-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          command: npm test
  coverage:
    docker:
      - image: dydxprotocol/node:12.18.3-alpine
      - image: trufflesuite/ganache-cli:v6.8.2
        command: -d -k=istanbul -i 1001
    working_directory: ~/build
    steps:
      - restore_cache:
          key: cache-completed-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Coverage
          command: npm run coverage
      - run:
          name: Coveralls
          command: cat coverage/lcov.info | node_modules/.bin/coveralls
  publish:
    docker:
      - image: dydxprotocol/node:12.18.3-alpine
    working_directory: ~/build
    steps:
      - restore_cache:
          key: cache-completed-build-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            - "sUNBaY12LhlRvWoAZgFJorDbQDtXUiheNAAK+2Ds33Q"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/build/.npmrc
      - run:
          command: |
            ./scripts/publish-if-not-exists.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_and_install:
          context: Node Service Context
      - lint:
          context: Node Service Context
          requires:
            - checkout_and_install
      - build:
          context: Node Service Context
          requires:
            - checkout_and_install
      - test:
          context: Node Service Context
          requires:
            - build
            - checkout_and_install
      - coverage:
          context: Node Service Context
          requires:
            - build
            - checkout_and_install
      - publish:
          context: Node Service Context
          requires:
            - lint
            - build
            - test
          filters:
            branches:
              only: master
