name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  main:
    uses: dydxprotocol/actions-public/.github/workflows/v3-publish-to-npm.yml@main
    secrets: inherit
    permissions:
      contents: write
